using System;
using System.IO;
using System.Text;

namespace DoaneDevTools.Vsix.Services
{
    /// <summary>
    /// Generates and installs a .git/hooks/pre-commit script that blocks commits
    /// containing high-confidence secret patterns. Complements the DSSEC Roslyn analyzer
    /// with a git-layer catch for non-C# files (.env, YAML, JSON configs, etc.).
    /// </summary>
    public static class PreCommitHookInstaller
    {
        public static void InstallOrUpdate(string repoRoot)
        {
            var hooksDir = Path.Combine(repoRoot, ".git", "hooks");
            if (!Directory.Exists(hooksDir)) return;

            var hookPath = Path.Combine(hooksDir, "pre-commit");
            var script = BuildHookScript();

            File.WriteAllText(hookPath, script, new UTF8Encoding(false));

            // Make executable on Unix-like systems
            if (Environment.OSVersion.Platform != PlatformID.Win32NT)
            {
                try
                {
                    System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                    {
                        FileName = "chmod",
                        Arguments = $"+x \"{hookPath}\"",
                        UseShellExecute = false,
                        CreateNoWindow = true
                    })?.WaitForExit();
                }
                catch { /* chmod not available; hook still runs on Windows */ }
            }
        }

        private static string BuildHookScript() => @"#!/bin/sh
# DoaneDevTools Secret Scanner pre-commit hook
# Generated by DoaneDevTools — do not remove this comment

FAIL=0

check_pattern() {
    FILE=""$1""
    PATTERN=""$2""
    LABEL=""$3""

    if git show :""$FILE"" 2>/dev/null | grep -qiE ""$PATTERN""; then
        echo ""[DSSEC] Possible $LABEL found in staged: $FILE""
        FAIL=1
    fi
}

# Get list of staged files
STAGED=$(git diff --cached --name-only --diff-filter=ACM)

for FILE in $STAGED; do
    # Skip binary and lock files
    case ""$FILE"" in
        *.png|*.jpg|*.gif|*.ico|*.exe|*.dll|*.pdb|*.zip|*.lock) continue ;;
    esac

    check_pattern ""$FILE"" ""password\s*=\s*['""][^'""]{6,}"" ""password""
    check_pattern ""$FILE"" ""api[_-]?key\s*=\s*['""][^'""]{10,}"" ""API key""
    check_pattern ""$FILE"" ""secret\s*=\s*['""][^'""]{10,}"" ""secret""
    check_pattern ""$FILE"" ""Bearer\s+[A-Za-z0-9+/=_\-]{20,}"" ""Bearer token""
    check_pattern ""$FILE"" ""AKIA[0-9A-Z]{16}"" ""AWS access key""
    check_pattern ""$FILE"" ""sk_(live|test)_[A-Za-z0-9]{20,}"" ""Stripe key""
    check_pattern ""$FILE"" ""ghp_[A-Za-z0-9]{36}"" ""GitHub PAT""
    check_pattern ""$FILE"" ""glpat-[A-Za-z0-9\-_]{20}"" ""GitLab PAT""
    check_pattern ""$FILE"" ""Server=.{5,};.{0,30}Password=[^;]{3,}"" ""connection string with password""
done

if [ ""$FAIL"" -ne 0 ]; then
    echo """"
    echo ""[DSSEC] Commit blocked: suspected secrets in staged files.""
    echo ""Move sensitive values to .env files or environment variables.""
    echo ""To bypass (NOT RECOMMENDED): git commit --no-verify""
    exit 1
fi

exit 0
";
    }
}
