using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.Json;
using DoaneDevTools.ToolWindows.TemplateBuilder.Models;

namespace DoaneDevTools.ToolWindows.TemplateBuilder.Services
{
    /// <summary>
    /// Discovers, loads, and executes scaffolding templates.
    ///
    /// Templates are loaded from two locations (merged, user templates take precedence):
    /// 1. Built-in templates shipped alongside this assembly in the <c>Templates/</c> subdirectory.
    /// 2. Custom user templates in <c>%APPDATA%\DoaneDevTools\templates\</c>.
    ///
    /// Each template is a directory containing a <c>template.json</c> manifest plus
    /// source files.  Variables are substituted using <c>{{ variable_name }}</c> markers
    /// (double-brace, Jinja2-compatible syntax).
    /// </summary>
    public class TemplateService
    {
        // -----------------------------------------------------------------------
        // Paths
        // -----------------------------------------------------------------------

        private static string BuiltInTemplatesDir =>
            Path.Combine(
                Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) ?? AppContext.BaseDirectory,
                "Templates");

        private static string UserTemplatesDir =>
            Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
                "DoaneDevTools", "templates");

        private static readonly JsonSerializerOptions _jsonOpts = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
            AllowTrailingCommas         = true,
            ReadCommentHandling         = JsonCommentHandling.Skip
        };

        // -----------------------------------------------------------------------
        // Public API
        // -----------------------------------------------------------------------

        /// <summary>
        /// Returns all available templates (built-in + user) grouped by category.
        /// User templates override built-in templates with the same <c>Name</c>.
        /// </summary>
        public List<TemplateManifest> GetTemplates()
        {
            var manifests = new Dictionary<string, TemplateManifest>(StringComparer.OrdinalIgnoreCase);

            // Load built-in templates first.
            foreach (var manifest in LoadTemplatesFromDirectory(BuiltInTemplatesDir))
                manifests[manifest.Name] = manifest;

            // User templates override built-in ones.
            if (Directory.Exists(UserTemplatesDir))
            {
                foreach (var manifest in LoadTemplatesFromDirectory(UserTemplatesDir))
                    manifests[manifest.Name] = manifest;
            }

            return manifests.Values.OrderBy(m => m.Category).ThenBy(m => m.Name).ToList();
        }

        /// <summary>
        /// Renders a single template file and returns the resulting string.
        /// </summary>
        public string RenderTemplate(string templateFilePath, Dictionary<string, string> variables)
        {
            if (!File.Exists(templateFilePath))
                return string.Empty;

            var content = File.ReadAllText(templateFilePath, Encoding.UTF8);
            return SubstituteVariables(content, variables);
        }

        /// <summary>
        /// Generates all output files for a template into <paramref name="outputPath"/>.
        /// Each output file in the manifest is rendered and written to disk.
        /// </summary>
        public void GenerateTemplate(
            TemplateManifest manifest,
            Dictionary<string, string> variables,
            string outputPath)
        {
            if (string.IsNullOrWhiteSpace(outputPath))
                throw new ArgumentException("Output path must not be empty.", nameof(outputPath));

            Directory.CreateDirectory(outputPath);

            foreach (var outputFile in manifest.OutputFiles)
            {
                var templateFilePath = Path.Combine(manifest.TemplateDirectory, outputFile);
                if (!File.Exists(templateFilePath))
                {
                    // Generate an empty placeholder so all declared files exist.
                    File.WriteAllText(
                        Path.Combine(outputPath, outputFile),
                        $"# Generated by DoaneDevTools — template file missing: {outputFile}\n",
                        Encoding.UTF8);
                    continue;
                }

                var rendered     = RenderTemplate(templateFilePath, variables);
                var destFileName = SubstituteVariables(outputFile, variables);
                var destPath     = Path.Combine(outputPath, destFileName);

                // Ensure subdirectories within the output file path exist.
                var destDir = Path.GetDirectoryName(destPath);
                if (!string.IsNullOrEmpty(destDir))
                    Directory.CreateDirectory(destDir);

                File.WriteAllText(destPath, rendered, Encoding.UTF8);
            }
        }

        // -----------------------------------------------------------------------
        // Private — template discovery
        // -----------------------------------------------------------------------

        private static IEnumerable<TemplateManifest> LoadTemplatesFromDirectory(string rootDir)
        {
            if (!Directory.Exists(rootDir))
                yield break;

            foreach (var templateDir in Directory.EnumerateDirectories(rootDir))
            {
                var manifestPath = Path.Combine(templateDir, "template.json");
                if (!File.Exists(manifestPath)) continue;

                TemplateManifest? manifest = null;
                try
                {
                    var json = File.ReadAllText(manifestPath, Encoding.UTF8);
                    manifest = JsonSerializer.Deserialize<TemplateManifest>(json, _jsonOpts);
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(
                        $"[TemplateService] Failed to parse {manifestPath}: {ex.Message}");
                }

                if (manifest == null) continue;
                manifest.TemplateDirectory = templateDir;
                yield return manifest;
            }
        }

        // -----------------------------------------------------------------------
        // Private — variable substitution
        // -----------------------------------------------------------------------

        /// <summary>
        /// Replaces all <c>{{ variable_name }}</c> tokens with their values.
        /// Unrecognised tokens are left as-is so template authors can use Jinja2
        /// syntax for actual runtime templates without conflicts.
        /// </summary>
        private static string SubstituteVariables(string content, Dictionary<string, string> variables)
        {
            if (string.IsNullOrEmpty(content) || !variables.Any())
                return content;

            var sb = new StringBuilder(content.Length + 64);
            int start = 0;

            while (start < content.Length)
            {
                int open = content.IndexOf("{{", start, StringComparison.Ordinal);
                if (open < 0)
                {
                    sb.Append(content, start, content.Length - start);
                    break;
                }

                int close = content.IndexOf("}}", open + 2, StringComparison.Ordinal);
                if (close < 0)
                {
                    sb.Append(content, start, content.Length - start);
                    break;
                }

                // Append literal content before the token.
                sb.Append(content, start, open - start);

                var key = content.Substring(open + 2, close - open - 2).Trim();

                if (variables.TryGetValue(key, out var replacement))
                    sb.Append(replacement);
                else
                    sb.Append("{{").Append(key).Append("}}");   // leave unknown tokens intact

                start = close + 2;
            }

            return sb.ToString();
        }
    }
}
