"""
{{ service_name }} — Flask + SQLAlchemy service
Generated by DoaneDevTools Template Builder.
"""

import logging
import os
import sys
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request, abort
from sqlalchemy.exc import SQLAlchemyError

load_dotenv()

from db import SessionLocal, ping_db
from models import ExampleRecord

# ---------------------------------------------------------------------------
# Structured JSON logging
# ---------------------------------------------------------------------------

class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        import json
        payload = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "level":     record.levelname,
            "logger":    record.name,
            "message":   record.getMessage(),
            "service":   "{{ service_name }}",
        }
        if record.exc_info:
            payload["exception"] = self.formatException(record.exc_info)
        return json.dumps(payload)


def configure_logging() -> None:
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(JsonFormatter())
    root = logging.getLogger()
    root.setLevel(os.getenv("LOG_LEVEL", "INFO").upper())
    root.handlers = [handler]


configure_logging()
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Flask application
# ---------------------------------------------------------------------------

app = Flask(__name__)
PORT = int(os.getenv("PORT", {{ port }}))


@app.route("/health")
def health():
    db_ok = ping_db()
    status = "ok" if db_ok else "degraded"
    code   = 200 if db_ok else 503
    return jsonify({
        "status":    status,
        "service":   "{{ service_name }}",
        "database":  "connected" if db_ok else "unreachable",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }), code


@app.route("/records", methods=["GET"])
def list_records():
    db = SessionLocal()
    try:
        records = db.query(ExampleRecord).limit(100).all()
        return jsonify([r.to_dict() for r in records])
    except SQLAlchemyError as exc:
        log.error("DB query failed: %s", exc)
        abort(500, description="Database error")
    finally:
        db.close()


@app.route("/records", methods=["POST"])
def create_record():
    data = request.get_json(force=True) or {}
    name = data.get("name", "").strip()
    if not name:
        abort(400, description="'name' is required")

    db = SessionLocal()
    try:
        record = ExampleRecord(name=name)
        db.add(record)
        db.commit()
        db.refresh(record)
        return jsonify(record.to_dict()), 201
    except SQLAlchemyError as exc:
        db.rollback()
        log.error("DB insert failed: %s", exc)
        abort(500, description="Database error")
    finally:
        db.close()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    log.info("Starting {{ service_name }} on port %d", PORT)
    app.run(host="0.0.0.0", port=PORT,
            debug=os.getenv("FLASK_DEBUG", "0") == "1")
