"""
db.py — SQLAlchemy engine + session factory for {{ service_name }}.
Generated by DoaneDevTools Template Builder.
"""

import os
from sqlalchemy import create_engine, text
from sqlalchemy.orm import DeclarativeBase, sessionmaker

# ---------------------------------------------------------------------------
# Connection string
# ---------------------------------------------------------------------------
# Prefer an explicit CONNECTION_STRING env-var; fall back to constructing one
# from individual parts so start-local.ps1 can set minimal vars.
# ---------------------------------------------------------------------------

def _build_connection_string() -> str:
    explicit = os.getenv("CONNECTION_STRING")
    if explicit:
        return explicit

    server = os.getenv("DB_SERVER", "{{ db_server }}")
    db     = os.getenv("DB_NAME",   "{{ db_name }}")
    driver = os.getenv("DB_DRIVER", "ODBC Driver 18 for SQL Server")
    return (
        f"mssql+pyodbc://@{server}/{db}"
        f"?driver={driver.replace(' ', '+')}"
        "&Trusted_Connection=yes"
        "&TrustServerCertificate=yes"
    )


engine = create_engine(
    _build_connection_string(),
    pool_pre_ping=True,
    pool_size=5,
    max_overflow=10,
    echo=os.getenv("SQL_ECHO", "0") == "1",
)

SessionLocal = sessionmaker(bind=engine, autocommit=False, autoflush=False)


# ---------------------------------------------------------------------------
# Declarative base
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Dependency helper (usable with Flask g / FastAPI Depends pattern)
# ---------------------------------------------------------------------------

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def ping_db() -> bool:
    """Returns True if the database is reachable."""
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False
