# start-local.ps1 — Generated by DoaneDevTools
param([switch]$ForceDeps)

$ErrorActionPreference = "Stop"
$Log    = "{{ service_name }}.log"
$LogErr = "{{ service_name }}.err.log"
if (Test-Path $Log)    { Remove-Item $Log }
if (Test-Path $LogErr) { Remove-Item $LogErr }

if ($ForceDeps -or -not (Test-Path ".venv")) {
    Write-Host "[{{ service_name }}] Creating virtual environment..." -ForegroundColor Cyan
    python -m venv .venv
    .\.venv\Scripts\pip install -r requirements.txt
}

.\.venv\Scripts\Activate.ps1

$env:FLASK_APP   = "app.py"
$env:FLASK_DEBUG = if ($env:FLASK_ENV -eq "development") { "1" } else { "0" }
$env:DB_SERVER   = "{{ db_server }}"
$env:DB_NAME     = "{{ db_name }}"

if (Test-Path ".env") {
    Get-Content ".env" | ForEach-Object {
        if ($_ -match "^\s*([^#][^=]*)\s*=\s*(.*)\s*$") {
            [System.Environment]::SetEnvironmentVariable($matches[1].Trim(), $matches[2].Trim(), "Process")
        }
    }
}

Write-Host "[{{ service_name }}] Starting on http://localhost:{{ port }}" -ForegroundColor Green
python -u app.py 2>&1 | Tee-Object -FilePath $Log
