"""
{{ service_name }} — Minimal Flask service
Generated by DoaneDevTools Template Builder.
"""

import logging
import os
import sys
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify

load_dotenv()

# ---------------------------------------------------------------------------
# Structured JSON logging
# ---------------------------------------------------------------------------

class JsonFormatter(logging.Formatter):
    """Emit log records as single-line JSON for log-aggregator ingestion."""

    def format(self, record: logging.LogRecord) -> str:
        import json
        payload = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
            "service": "{{ service_name }}",
        }
        if record.exc_info:
            payload["exception"] = self.formatException(record.exc_info)
        return json.dumps(payload)


def configure_logging() -> None:
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(JsonFormatter())
    root = logging.getLogger()
    root.setLevel(os.getenv("LOG_LEVEL", "INFO").upper())
    root.handlers = [handler]


configure_logging()
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Flask application
# ---------------------------------------------------------------------------

app = Flask(__name__)
PORT = int(os.getenv("PORT", {{ port }}))


@app.route("/health")
def health():
    """Liveness/readiness probe — returns 200 OK with service metadata."""
    return jsonify({
        "status": "ok",
        "service": "{{ service_name }}",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })


@app.route("/")
def index():
    return jsonify({"service": "{{ service_name }}", "status": "running"})


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    log.info("Starting {{ service_name }} on port %d", PORT)
    app.run(host="0.0.0.0", port=PORT,
            debug=os.getenv("FLASK_DEBUG", "0") == "1")
