// {{ service_name }} — ASP.NET Core Minimal Web API
// Generated by DoaneDevTools Template Builder.

using Serilog;
using Serilog.Events;

// ---------------------------------------------------------------------------
// Bootstrap logger (captures startup errors before host is built)
// ---------------------------------------------------------------------------
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
    .Enrich.FromLogContext()
    .WriteTo.Console(outputTemplate:
        "[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext}: {Message:lj}{NewLine}{Exception}")
    .CreateBootstrapLogger();

try
{
    Log.Information("Starting {{ service_name }}");

    var builder = WebApplication.CreateBuilder(args);

    // ---------------------------------------------------------------------------
    // Serilog
    // ---------------------------------------------------------------------------
    builder.Host.UseSerilog((ctx, services, cfg) => cfg
        .ReadFrom.Configuration(ctx.Configuration)
        .ReadFrom.Services(services)
        .Enrich.FromLogContext()
        .WriteTo.Console());

    // ---------------------------------------------------------------------------
    // Services
    // ---------------------------------------------------------------------------
    builder.Services.AddEndpointsApiExplorer();
    builder.Services.AddSwaggerGen(options =>
    {
        options.SwaggerDoc("{{ api_version }}", new Microsoft.OpenApi.Models.OpenApiInfo
        {
            Title   = "{{ service_name }}",
            Version = "{{ api_version }}"
        });
    });

    builder.Services.AddHealthChecks();

    // ---------------------------------------------------------------------------
    // Application
    // ---------------------------------------------------------------------------
    var app = builder.Build();

    app.UseSerilogRequestLogging();

    if (app.Environment.IsDevelopment())
    {
        app.UseSwagger();
        app.UseSwaggerUI(options =>
            options.SwaggerEndpoint("/swagger/{{ api_version }}/swagger.json", "{{ service_name }} {{ api_version }}"));
    }

    app.UseHttpsRedirection();

    // Health endpoint
    app.MapHealthChecks("/health").WithTags("Health");

    // Versioned route group
    var api = app.MapGroup("/api/{{ api_version }}");

    api.MapGet("/", () => Results.Ok(new
    {
        service   = "{{ service_name }}",
        version   = "{{ api_version }}",
        timestamp = DateTimeOffset.UtcNow
    }))
    .WithName("GetRoot")
    .WithOpenApi();

    // ---------------------------------------------------------------------------
    // Example resource endpoints — replace with domain logic
    // ---------------------------------------------------------------------------
    api.MapGet("/items", () => Results.Ok(Array.Empty<object>()))
       .WithName("GetItems")
       .WithOpenApi();

    api.MapGet("/items/{id:int}", (int id) => Results.NotFound())
       .WithName("GetItem")
       .WithOpenApi();

    api.MapPost("/items", (object body) => Results.Created($"/api/{{ api_version }}/items/1", body))
       .WithName("CreateItem")
       .WithOpenApi();

    await app.RunAsync();
    return 0;
}
catch (Exception ex) when (ex is not OperationCanceledException)
{
    Log.Fatal(ex, "{{ service_name }} terminated unexpectedly");
    return 1;
}
finally
{
    await Log.CloseAndFlushAsync();
}
